# Generated by Django 4.0.3 on 2022-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('publ_date', models.CharField(max_length=10)),
                ('ISBN_number', models.CharField(max_length=13)),
                ('page_count', models.PositiveIntegerField()),
                ('cover_URL', models.URLField()),
                ('publ_language', models.CharField(max_length=20)),
            ],
        ),
    ]
