# Generated by Django 4.0.3 on 2022-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_isbn_number_alter_books_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
